modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/PalTheTaur/Enhanced-Stockpile/issues"
license = "MIT License"

[[mods]]
modId = "enhanced_stockpile"
version = "${version}"
displayName = "Enhanced Threshold Switch"
authors = "PalTheTaur"
description = '''
Makes threshold switches able to work with mechanical bearings
'''
logoFile = "icon.png"

[[dependencies.enhanced_stockpile]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_stockpile]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_stockpile]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"